"""Initial migration

Revision ID: 6a5cd006ee18
Revises: 
Create Date: 2022-07-07 20:26:29.788324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a5cd006ee18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('artist', sa.Text(), nullable=False),
    sa.Column('album', sa.Text(), nullable=True),
    sa.Column('track', sa.Text(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs')
    # ### end Alembic commands ###
