from node:lts-alpine as builder

RUN mkdir /app

WORKDIR /app

COPY . .

RUN npm install 


RUN npm run build


from node:lts-alpine as web

RUN npm install -g http-server

COPY --from=builder /app/dist /app

CMD ["/app", "-P http://localhost:80?", "-p 80"]
ENTRYPOINT ["http-server"]
